repos:
- hooks:
  - id: ruff
    args: [ --fix ]
  - id: ruff-format
  repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.7
- hooks:
  - id: commitizen
  - id: commitizen-branch
    stages:
    - push
  repo: https://github.com/commitizen-tools/commitizen
  rev: v3.12.0
